all:
	diff intermediate-results.csv expected-intermediate-results.csv
	diff Bastiaan-results.csv expected-Bastiaan-results.csv

update:
	cp intermediate-results.csv expected-intermediate-results.csv
	cp Bastiaan-results.csv expected-Bastiaan-results.csv
